version: "3.3"
services:
  frontend:
    container_name: kpd-frontend
    build: ./frontend
    restart:
      unless-stopped
    ports:
      - "8081:80"
  backend:
    container_name: kpd-backend
    build: ./backend
    networks:
      - backend-database
    restart: "unless-stopped"
    ports:
      - "4000:3001"
    env_file:
          - ./.env
    depends_on:
      - db
    links:
      - db
  db:
    container_name: kpd-db
    image: "postgres"
    env_file:
      - ./.env
    networks:
      - backend-database
    restart: unless-stopped
    volumes:
     - db:/var/lib/postgresql/data
     - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
 db:
   driver: local
