version: "3.9"
services:
  frontend:
    container_name: kpd-frontend
    build: ./frontend
    restart:
      unless-stopped
    ports:
      - "8081:80"
  backend:
    container_name: kpd-backend
    build: ./backend
    restart: "unless-stopped"
    ports:
      - "4000:3001"
    env_file:
          - ./.env
    depends_on:
      - db
    links:
      - db
    healthcheck:
      test: "wget -nv -t1 --spider 'http://localhost:3001/'"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  db:
    image: "postgres"
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
          - POSTGRES_USER=student
          - POSTGRES_PASSWORD=student
          - POSTGRES_DB=kupipodariday
    volumes:
     - db:/var/lib/postgresql/data
     - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
 db:
   driver: local
